### ISSUE TITLE
Duda sobre descarga de imágenes

### ISSUE THREAD

**Issue by isaaclopez77** [mawrkus/jason-the-miner#17]
Muy buenas, 
lo primero es darte las gracias por tu trabajo, después de un par de días de aprendizaje estoy usando tu scraper y me está siendo muy útil a mi y a mi empresa.
Estoy usando una matriz de transformadores para que, a la vez que consigo los detalles de una búsqueda de productos de amazon, poder descargar sus imágenes. He conseguido ambas cosas por separado, pero estoy tratando de hacerlo en un mismo archivo json:

...
"transform": [{
    "download-file": {
      "folder": "imgs/",
      "namePattern": "producto-{index}",
      "concurrency": 2,
      "maxSizeInMb": 1
    },
    "csv-file": {
      "path": "resultados-productos.csv"
    }
  }]
...
Éste es el código usando una matriz de transformadores.
Cuando ejecuto el código desde la línea de comandos, imprime una cadena JSON con los resultados del scrapeo. Pero no crea el archivo CSV ni descarga las imágenes.
¿Que puede estar pasando? ¿Esta sintaxis es incorrecta?  Muchas gracias.

**Comment by mawrkus** [comment]
Hola Isaac,

Con la version de Jason en master todavia no se puede utilizar una matriz de transformadores. Pero estoy trabajando en poder hacerlo en https://github.com/mawrkus/jason-the-miner/pull/14 (rama "small-fixes" :p), mira el [README](https://github.com/mawrkus/jason-the-miner/tree/small-fixes#transformers).
Dicho esto, ya puedes utilizar la version en esta rama (es bastante estable). Solo tendras que crear una config similar a:

```json
{
  "load": {
    "http": {
      "baseURL": "https://www.goodreads.com",
      "url": "/list/show/11.Best_Crime_Mystery_Books"
    }
  },
  "parse": {
    "html": {
      "books": [{
        "_$": ".tableList tr ? slice(0, 3)",
        "title": "td .bookTitle > span | trim",
        "cover": ".bookSmallImg < attr(src)"
      }]
    }
  },
  "transform": [{
    "csv-file": {
      "path": "demos/data/out/goodreads-list.csv",
      "csv": {
        "header": true,
        "delimiter": ";"
      }
    }
  }, {
    "download-file": {
      "parseSelector": "cover",
      "folder": "./demos/data/out/downloads",
      "concurrency": 3,
      "namePattern": "{index}-{name}"
    }
  }]
}
```

**Comment by isaaclopez77** [comment]
Buenas de nuevo, gracias por la repuesta.
Sigue sin funcionar, he copiado y pegado tu código en un archivo llamado pruebaa.json y al ejecutarlo con jason-the-miner -c pruebaa.json la salida es la que aparece en el archivo que adjunto.
No crea ningún csv ni ninguna imagen en el directorio que le he indicado.
¿Dónde puede estar el problema
![captura](https://user-images.githubusercontent.com/15193498/46400153-04d52000-c6fa-11e8-8d5e-7c5bcef975ad.PNG)
?

**Comment by mawrkus** [comment]
Creo que no estas utilizando la version que esta en la rama "small-fixes" pero la version instalada en global. Si has clonado la version de esta rama en tu carpeta `/home/isaac/jason-the-miner`, tendras que ejecutar `node ./bin/jason-the-miner.js -c ./pruebaa.json`

**Comment by mawrkus** [comment]
Todo bien? Cerramos esta issue?
